package com.example.corbaclient.corba.huawei.HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, March 18, 2023 1:09:07 PM ICT
*/

public interface HelloOperations 
{
  String getListCustomer ();
  String getDetailCustomer ();
} // interface HelloOperations
